CREATE TABLE Roles(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
RoleName NVARCHAR(20) NOT NULL
);

CREATE TABLE Users(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Username VARCHAR(16) NOT NULL,
Password VARCHAR(16) NOT NULL,
RoleId INT NOT NULL FOREIGN KEY REFERENCES Roles(Id),
FullName NVARCHAR(100)
);

CREATE TABLE Product(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
ItemNumber NVARCHAR(255) NOT NULL,
ProductName NVARCHAR(255) NOT NULL,
Width FLOAT NOT NULL,
Length FLOAT NOT NULL,
Image NVARCHAR(500),
Notes NVARCHAR(500)
);

CREATE TABLE Fabric(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
ItemNumber NVARCHAR(255) NOT NULL,
FabricName NVARCHAR(200) NOT NULL,
Color NVARCHAR(100),
Pattern NVARCHAR(100),
Image NVARCHAR(500),
Composition NVARCHAR(500),
Width FLOAT NOT NULL,
Length FLOAT NOT NULL,
Price INT NOT NULL
);

CREATE TABLE AccessoryType(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
TypeName NVARCHAR(255) NOT NULL
);

CREATE TABLE OrderStage(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
StageName NVARCHAR(100) NOT NULL
);

CREATE TABLE Accessories(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
ItemNumber NVARCHAR(255) NOT NULL,
AccessoryName NVARCHAR(255) NOT NULL,
TypeId INT NOT NULL FOREIGN KEY REFERENCES AccessoryType(Id),
Width FLOAT NOT NULL,
Length FLOAT,
Weight FLOAT,
Image NVARCHAR(500),
Price INT NOT NULL
);

CREATE TABLE Orders(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Date DATE NOT NULL,
Stage NVARCHAR(20) NOT NULL,
ClientId INT NOT NULL FOREIGN KEY REFERENCES Users(Id),
ManagerId INT FOREIGN KEY REFERENCES Users(Id),
Price INT
);

CREATE TABLE OrderProduct(
OrderId INT NOT NULL FOREIGN KEY REFERENCES Orders(Id),
ProductId INT NOT NULL FOREIGN KEY REFERENCES Product(Id),
Quantity INT NOT NULL,
PRIMARY KEY(OrderId, ProductId)
);

CREATE TABLE FabricProduct(
FabricId INT NOT NULL FOREIGN KEY REFERENCES Fabric(Id),
ProductId INT NOT NULL FOREIGN KEY REFERENCES Product(Id),
PRIMARY KEY(FabricId, ProductId)
);

CREATE TABLE StorageFabric(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
FabricId INT NOT NULL FOREIGN KEY REFERENCES Fabric(Id),
Width FLOAT NOT NULL,
Length FLOAT NOT NULL
);

CREATE TABLE AccessoryProduct(
AccessoryId INT NOT NULL FOREIGN KEY REFERENCES Accessories(Id),
ProductId INT NOT NULL FOREIGN KEY REFERENCES Product(Id),
Location NVARCHAR(100) NOT NULL,
Width FLOAT,
Length FLOAT,
Turn INT,
Quantity INT NOT NULL
);

CREATE TABLE StorageAccessories(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
AccessoryId INT NOT NULL FOREIGN KEY REFERENCES Accessories(Id),
Quantity INT NOT NULL
);