//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sewing.AuxClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessoryProduct
    {
        public int AccessoryId { get; set; }
        public int ProductId { get; set; }
        public string Location { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<int> Turn { get; set; }
        public int Quantity { get; set; }
    
        public virtual Accessories Accessories { get; set; }
        public virtual Product Product { get; set; }
    }
}
