//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sewing.AuxClasses
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sewingEntities : DbContext
    {
        public sewingEntities()
            : base("name=sewingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accessories> Accessories { get; set; }
        public virtual DbSet<AccessoryType> AccessoryType { get; set; }
        public virtual DbSet<Fabric> Fabric { get; set; }
        public virtual DbSet<OrderProduct> OrderProduct { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<OrderStage> OrderStage { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<StorageAccessories> StorageAccessories { get; set; }
        public virtual DbSet<StorageFabric> StorageFabric { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<AccessoryProduct> AccessoryProduct { get; set; }
    }
}
