//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sewing.AuxClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageFabric
    {
        public int Id { get; set; }
        public int FabricId { get; set; }
        public double Width { get; set; }
        public double Length { get; set; }
    
        public virtual Fabric Fabric { get; set; }
    }
}
